spring:
    datasource:
        url: jdbc:h2:mem:bbs
        driverClassName: org.h2.Driver
        username: application
        password: 981723qwqw!
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
